site_name: TPT generator doc
nav:
    - Overview: index.md
    - Methodology: methodology.md
    - Developer guide: developer.md
    - Reference: reference.md
theme:
    name: "material"
    logo: "5d07dc3917bf6193f2e37f9b_logo-AO.svg"
    favicon: "5d0b30400369a4cb0ed33ef4_AO-favicon.png"
plugins:
    - search
    - mkdocstrings
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - admonition
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg