FIELDS = {
    "1" : r"1_Portfolio identifying data",
    "2" : r"2_Type of identification code for the fund share or portfolio",
    "3" : r"3_Portfolio name",
    "4" : r"4_Portfolio currency (B)",
    "5" : r"5_Net asset valuation of the portfolio or the share class in portfolio currency",
    "6" : r"6_Valuation date",
    "7" : r"7_Reporting date",
    "8" : r"8_Share price",
    "8b" : r"8b_Total number of shares",
    "9" : r"9_% cash",
    "10" : r"10_Portfolio Modified Duration",
    "11" : r"11_Complete SCR Delivery",
    "12" : r"12_CIC code of the instrument",
    "13" : r"13_Economic zone of the quotation place",
    "14" : r"14_Identification code of the financial instrument",
    "15" : r"15_Type of identification code for the instrument",
    "16" : r"16_Grouping code for multiple leg instruments",
    "17" : r"17_Instrument name",
    "17b" : r"17b_Asset / Liability",
    "18" : r"18_Quantity",
    "19" : r"19_Nominal amount",
    "20" : r"20_Contract size for derivatives",
    "21" : r"21_Quotation currency (A)",
    "22" : r"22_Market valuation in quotation currency (A)",
    "23" : r"23_Clean market valuation in quotation currency (A)",
    "24" : r"24_Market valuation in portfolio currency (B)",
    "25" : r"25_Clean market valuation in portfolio currency (B)",
    "26" : r"26_Valuation weight",
    "27" : r"27_Market exposure amount in quotation currency (A)",
    "28" : r"28_Market exposure amount in portfolio currency (B)",
    "29" : r"29_Market exposure amount for the 3rd currency in quotation currency of the underlying asset (C)",
    "30" : r"30_Market Exposure in weight",
    "31" : r"31_Market exposure for the 3rd currency in weight over NAV",
    "32" : r"32_Interest rate type",
    "33" : r"33_Coupon rate",
    "34" : r"34_Interest rate reference identification",
    "35" : r"35_Identification type for interest rate index",
    "36" : r"36_Interest rate index name",
    "37" : r"37_Interest rate Margin",
    "38" : r"38_Coupon payment frequency",
    "39" : r"39_Maturity date",
    "40" : r"40_Redemption type",
    "41" : r"41_Redemption rate",
    "42" : r"42_Callable / putable",
    "43" : r"43_Call / put date",
    "44" : r"44_Issuer / bearer option exercise",
    "45" : r"45_Strike price for embedded (call/put) options",
    "46" : r"46_Issuer name",
    "47" : r"47_Issuer identification code",
    "48" : r"48_Type of identification code for issuer",
    "49" : r"49_Name of the group of the issuer",
    "50" : r"50_Identification of the group",
    "51" : r"51_Type of identification code for issuer group",
    "52" : r"52_Issuer country",
    "53" : r"53_Issuer economic area",
    "54" : r"54_Economic sector",
    "55" : r"55_Covered / not covered",
    "56" : r"56_Securitisation",
    "57" : r"57_Explicit guarantee by the country of issue",
    "58" : r"58_Subordinated debt",
    "58b" : r"58b_Nature of the TRANCHE",
    "59" : r"59_Credit quality step",
    "60" : r"60_Call / Put / Cap / Floor",
    "61" : r"61_Strike price",
    "62" : r"62_Conversion factor (convertibles) / concordance factor / parity (options)",
    "63" : r"63_Effective Date of Instrument",
    "64" : r"64_Exercise type",
    "65" : r"65_Hedging Rolling",
    "67" : r"67_CIC code of the underlying asset",
    "68" : r"68_Identification code of the underlying asset",
    "69" : r"69_Type of identification code for the underlying asset",
    "70" : r"70_Name of the underlying asset",
    "71" : r"71_Quotation currency of the underlying asset (C)",
    "72" : r"72_Last valuation price of the underlying asset",
    "73" : r"73_Country of quotation of the underlying asset",
    "74" : r"74_Economic Area of quotation of the underlying asset",
    "75" : r"75_Coupon rate of the underlying asset",
    "76" : r"76_Coupon payment frequency of the underlying asset",
    "77" : r"77_Maturity date of the underlying asset",
    "78" : r"78_Redemption profile of the underlying asset",
    "79" : r"79_Redemption rate of the underlying asset",
    "80" : r"80_Issuer name of the underlying asset",
    "81" : r"81_Issuer identification code of the underlying asset",
    "82" : r"82_Type of issuer identification code of the underlying asset",
    "83" : r"83_Name of the group of the issuer of the underlying asset",
    "84" : r"84_Identification of the group of the underlying asset",
    "85" : r"85_Type of the group identification code of the underlying asset",
    "86" : r"86_Issuer country of the underlying asset",
    "87" : r"87_Issuer economic area of the underlying asset",
    "88" : r"88_Explicit guarantee by the country of issue of the underlying asset",
    "89" : r"89_Credit quality step of the underlying asset",
    "90" : r"90_Modified Duration to maturity date",
    "91" : r"91_Modified duration to next option exercise date",
    "92" : r"92_Credit sensitivity",
    "93" : r"93_Sensitivity to underlying asset price (delta)",
    "94" : r"94_Convexity / gamma for derivatives",
    "94b" : r"94b_Vega",
    "95" : r"95_Identification of the original portfolio for positions embedded in a fund",
    "97" : r"97_SCR_Mrkt_IR_up weight over NAV",
    "98" : r"98_SCR_Mrkt_IR_down weight over NAV",
    "99" : r"99_SCR_Mrkt_Eq_type1 weight over NAV",
    "100" : r"100_SCR_Mrkt_Eq_type2 weight over NAV",
    "101" : r"101_SCR_Mrkt_Prop weight over NAV",
    "102" : r"102_SCR_Mrkt_Spread_bonds weight over NAV",
    "103" : r"103_SCR_Mrkt_Spread_structured weight over NAV",
    "104" : r"104_SCR_Mrkt_Spread_derivatives_up weight over NAV",
    "105" : r"105_SCR_Mrkt_Spread_derivatives_down weight over NAV",
    "105a" : r"105a_SCR_Mrkt_FX_up weight over NAV",
    "105b" : r"105b_SCR_Mrkt_FX_down weight over NAV",
    "106" : r"106_Asset pledged as collateral",
    "107" : r"107_Place of deposit",
    "108" : r"108_Participation",
    "110" : r"110_Valorisation method",
    "111" : r"111_Value of acquisition",
    "112" : r"112_Credit rating",
    "113" : r"113_Rating agency",
    "114" : r"114_Issuer economic area",
    "115" : r"115_Fund Issuer Code",
    "116" : r"116_Fund Issuer Code Type",
    "117" : r"117_Fund Issuer Name",
    "118" : r"118_Fund Issuer Sector",
    "119" : r"119_Fund Issuer Group Code",
    "120" : r"120_Fund Issuer Group Code Type",
    "121" : r"121_Fund Issuer Group name",
    "122" : r"122_Fund Issuer Country",
    "123" : r"123_Fund CIC code",
    "123a" : r"123a_Fund Custodian Country",
    "124" : r"124_Duration",
    "125" : r"125_Accrued Income (Security Denominated Currency)",
    "126" : r"126_Accrued Income (Portfolio Denominated Currency)",
    "127" : r"127_Bond Floor (convertible instrument only)",
    "128" : r"128_Option premium (convertible instrument only)",
    "129" : r"129_Valuation Yield",
    "130" : r"130_Valuation Z-spread",
    "131" : r"131_Underlying Asset Category",
    "132" : r"132_Infrastructure_investment",
    "133" : r"133_custodian_name",
    "134" : r"134_type1_private_equity_portfolio_eligibility",
    "135" : r"135_type1_private_equity_issuer_beta",
    "137" : r"137_counterparty_sector",
    "1000" : r"1000_TPT Version",
}

DB_INSTRUMENTS_INFOS_MAP = {
    'cic': '12_CIC code of the instrument',
    'economic_zone_of_the_quotation_place': '13_Economic zone of the quotation place',
    'identification_code': '14_Identification code of the financial instrument',
    'type_identification_code_for_the_instrument': '15_Type of identification code for the instrument',
    'contract_size_for_derivatives': '20_Contract size for derivatives',
    'quotation_currency': '21_Quotation currency (A)',
    'interest_rate_type': '32_Interest rate type',
    'coupon_rate': '33_Coupon rate',
    'interest_rate_reference_identification': '34_Interest rate reference identification',
    'identification_type_for_interest_rate_index': '35_Identification type for interest rate index',
    'interest_rate_index_name': '36_Interest rate index name',
    'interest_rate_margin': '37_Interest rate Margin',
    'coupon_payment_frequency': '38_Coupon payment frequency',
    'redemption_type': '40_Redemption type',
    'redemption_rate': '41_Redemption rate',
    'callable_puttable': '42_Callable / putable',
    'call_put_date': '43_Call / put date',
    'issuer_bearer_option_exercise': '44_Issuer / bearer option exercise',
    'strike_price_for_embedded_callput_options': '45_Strike price for embedded (call/put) options',
    'issuer_name': '46_Issuer name',
    'issuer_identification_code': '47_Issuer identification code',
    'name_of_the_group_of_the_issuer': '49_Name of the group of the issuer',
    'identification_of_the_group': '50_Identification of the group',
    'iso_code_2': '52_Issuer country',
    'Geographic': '53_Issuer economic area',
    'economic_sector': '54_Economic sector',
    'covered_not_covered': '55_Covered / not covered',
    'securitisation': '56_Securitisation',
    'explicit_guarantee_by_the_country_of_issue': '57_Explicit guarantee by the country of issue',
    'subordinated_debt': '58_Subordinated debt',
    'nature_of_the_tranche': '58b_Nature of the TRANCHE',
    'credit_quality_step': '59_Credit quality step',
    'call_put_cap_floor': '60_Call / Put / Cap / Floor',
    'strike_price': '61_Strike price',
    'conversion_factor_convertibles_concordance_factor_parity_options': '62_Conversion factor (convertibles) / concordance factor / parity (options)',
    'effective_date_of_instrument': '63_Effective Date of Instrument',
    'exercise_type': '64_Exercise type',
    'cic_code_of_the_underlying_asset': '67_CIC code of the underlying asset',
    'identification_code_of_the_underlying_asset': '68_Identification code of the underlying asset',
    'type_of_identification_code_for_the_underlying_asset': '69_Type of identification code for the underlying asset',
    'name_of_the_underlying_asset': '70_Name of the underlying asset',
    'quotation_currency_of_the_underlying_asset_c': '71_Quotation currency of the underlying asset (C)',
    'last_valuation_price_of_the_underlying_asset': '72_Last valuation price of the underlying asset',
    'country_of_quotation_of_the_underlying_asset': '73_Country of quotation of the underlying asset',
    'economic_area_of_quotation_of_the_underlying_asset': '74_Economic Area of quotation of the underlying asset',
    'coupon_rate_of_the_underlying_asset': '75_Coupon rate of the underlying asset',
    'coupon_payment_frequency_of_the_underlying_asset': '76_Coupon payment frequency of the underlying asset',
    'maturity_date_of_the_underlying_asset': '77_Maturity date of the underlying asset',
    'redemption_profile_of_the_underlying_asset': '78_Redemption profile of the underlying asset',
    'redemption_rate_of_the_underlying_asset': '79_Redemption rate of the underlying asset',
    'issuer_name_of_the_underlying_asset': '80_Issuer name of the underlying asset',
    'issuer_identification_code_of_the_underlying_asset': '81_Issuer identification code of the underlying asset',
    'type_of_issuer_identification_code_of_the_underlying_asset': '82_Type of issuer identification code of the underlying asset',
    'name_of_the_group_of_the_issuer_of_the_underlying_asset': '83_Name of the group of the issuer of the underlying asset',
    'identification_of_the_group_of_the_underlying_asset': '84_Identification of the group of the underlying asset',
    'type_of_the_group_identification_code_of_the_underlying_asset': '85_Type of the group identification code of the underlying asset',
    'issuer_country_of_the_underlying_asset': '86_Issuer country of the underlying asset',
    'issuer_economic_area_of_the_underlying_asset': '87_Issuer economic area of the underlying asset',
    'explicit_guarantee_by_the_country_of_issue_of_the_underlying_asset': '88_Explicit guarantee by the country of issue of the underlying asset',
    'credit_quality_step_of_the_underlying_asset': '89_Credit quality step of the underlying asset'
}

IN18 = [
    "29",
    "31",
    "32",
    "33",
    "34",
    "39",
    "41",
    "42",
    "43",
    "44",
    "45",
    "46",
    "47",
    "48",
    "49",
    "A1",
    "A2",
    "A3",
    "A5",
    "A7",
    "A8",
    "A9",
    "B1",
    "B4",
    "B5",
    "C1",
    "C4",
    "C5",
    "D1",
    "D4",
    "D5",
]

RATINGS = {
    "rating_moodys": {
        "Aaa"  : 1,
        "Aa1"  : 1,
        "Aa2"  : 1,
        "Aa3"  : 1,
        "A1"   : 2,
        "A2"   : 2,
        "A3"   : 2,
        "Baa1" : 3,
        "Baa2" : 3,
        "Baa3" : 3,
        "Ba1"  : 4,
        "Ba2"  : 4,
        "Ba3"  : 4,
        "B1"   : 5,
        "B2"   : 5,
        "B3"   : 5,
        "Caa1" : 6,
        "Caa2" : 6,
        "Caa3" : 6,
        "Ca"   : 6,
        "C"    : 6,
    },
    "rating_sp": {
        "AAA"  : 1,
        "AA+"  : 1,
        "AA"   : 1,
        "AA-"  : 1,
        "A+"   : 2,
        "A"    : 2,
        "A-"   : 2,
        "BBB+" : 3,
        "BBB"  : 3,
        "BBB-" : 3,
        "BB+"  : 4,
        "BB"   : 4,
        "BB-"  : 4,
        "B+"   : 5,
        "B"    : 5,
        "B-"   : 5,
        "CCC+" : 6,
        "CCC"  : 6,
        "CCC-" : 6,
        "CC"   : 6,
        "SD"   : 6,
        "D"    : 6,
    },
    "rating_fitch": {
        "AAA"  : 1,
        "AA+"  : 1,
        "AA"   : 1,
        "AA-"  : 1,
        "A+"   : 2,
        "A"    : 2,
        "A-"   : 2,
        "BBB+" : 3,
        "BBB"  : 3,
        "BBB-" : 3,
        "BB+"  : 4,
        "BB"   : 4,
        "BB-"  : 4,
        "B+"   : 5,
        "B"    : 5,
        "B-"   : 5,
        "CCC+" : 6,
        "CCC"  : 6,
        "CCC-" : 6,
        "CC"   : 6,
        "C"    : 6,
        "DDD"  : 6,
        "DD"   : 6,
        "D"    : 6,
    }
}

#RATINGS = {
#    "rating_moodys": {
#        "Aaa"  : 21,
#        "Aa1"  : 20,
#        "Aa2"  : 19,
#        "Aa3"  : 18,
#        "A1"   : 17,
#        "A2"   : 16,
#        "A3"   : 15,
#        "Baa1" : 14,
#        "Baa2" : 13,
#        "Baa3" : 12,
#        "Ba1"  : 11,
#        "Ba2"  : 10,
#        "Ba3"  : 9,
#        "B1"   : 8,
#        "B2"   : 7,
#        "B3"   : 6,
#        "Caa1" : 5,
#        "Caa2" : 4,
#        "Caa3" : 3,
#        "Ca"   : 2,
#        "C"    : 1,
#    },
#    "rating_sp": {
#        "AAA"  : 21,
#        "AA+"  : 20,
#        "AA"   : 19,
#        "AA-"  : 18,
#        "A+"   : 17,
#        "A"    : 16,
#        "A-"   : 15,
#        "BBB+" : 14,
#        "BBB"  : 13,
#        "BBB-" : 12,
#        "BB+"  : 11,
#        "BB"   : 10,
#        "BB-"  : 9,
#        "B+"   : 8,
#        "B"    : 7,
#        "B-"   : 6,
#        "CCC+" : 5,
#        "CCC"  : 4,
#        "CCC-" : 3,
#        "CC"   : 2,
#        "SD"   : 1,
#        "D"    : 1
#    },
#    "rating_fitch": {
#        "AAA"  : 21,
#        "AA+"  : 20,
#        "AA"   : 19,
#        "AA-"  : 18,
#        "A+"   : 17,
#        "A"    : 16,
#        "A-"   : 15,
#        "BBB+" : 14,
#        "BBB"  : 13,
#        "BBB-" : 12,
#        "BB+"  : 11,
#        "BB"   : 10,
#        "BB-"  : 9,
#        "B+"   : 8,
#        "B"    : 7,
#        "B-"   : 6,
#        "CCC+" : 5,
#        "CCC"  : 4,
#        "CCC-" : 3,
#        "CC"   : 2,
#        "C"    : 2,
#        "DDD"  : 1,
#        "DD"   : 1,
#        "D"    : 1,
#    }
#}
#
#RATING_TO_CQS_MAP = {
#    21 : 1,
#    20 : 1,
#    19 : 1,
#    18 : 1,
#    17 : 2,
#    16 : 2,
#    15 : 2,
#    14 : 3,
#    13 : 3,
#    12 : 3,
#    11 : 4,
#    10 : 4,
#    9  : 4,
#    8  : 5,
#    7  : 5,
#    6  : 5,
#    5  : 6,
#    4  : 6,
#    3  : 6,
#    2  : 6,
#    1  : 6,
#}